= Tutorial for the Jump The Queue Application
====
Jump The Queue is a small application based on the devonfw framework, which you can create yourself by following our simple step-by-step tutorial. By doing so, you will learn about the app development workflow and gain insight into the design of a professional business information system.

More information about Jump The Queue on https://github.com/devonfw/jump-the-queue
====

[step]
--
executeCommand("py -3 -m http.server 8001", "python3 -m http.server 8001",  {"asynchronous": true, "dir":"some/Dire"}, {"port": 8001, "startupTime": 15})
executeCommand("py -3 -m http.server 8002", "python3 -m http.server 8002",  {"asynchronous": true, "dir":"some/Dire" }, {"port": 8002, "startupTime": 15})
executeCommand("py -3 -m http.server 8003", "python3 -m http.server 8003",  {"asynchronous": true, "dir":"some/Dire"}, {"port": 8003, "startupTime": 15})
--

[step]
--
executeCommand("py -3 -m http.server 8004", "python3 -m http.server 8004",  {"asynchronous": true}, {"port": 8004, "startupTime": 15})
executeCommand("py -3 -m http.server 8005", "python3 -m http.server 8005",  {"asynchronous": true}, {"port": 8005, "startupTime": 15})
--


