= Tutorial for the Jump The Queue Application
====
Jump The Queue is a small application based on the devonfw framework, which you can create yourself by following our simple step-by-step tutorial. By doing so, you will learn about the app development workflow and gain insight into the design of a professional business information system.

More information about Jump The Queue on https://github.com/devonfw/jump-the-queue
====

[step]
--
executeCommand("py -3 -m http.server 8001", "python3 -m http.server 8001",  {"asynchronous": true, "dir":"some/Dire"}, {"port": 8001, "startupTime": 15})
executeCommand("py -3 -m http.server 8002", "python3 -m http.server 8002",  {"asynchronous": true, "dir":"some/Dire" }, {"port": 8002, "startupTime": 15})
executeCommand("py -3 -m http.server 8003", "python3 -m http.server 8003",  {"asynchronous": true, "dir":"some/Dire"}, {"port": 8003, "startupTime": 15})
--

[step]
--
executeCommand("somePollingScript.ps1","bash somePollingScript.sh", {"dir": "data/setup","asynchronous": true, "args": ["--params 5"]})
executeCommand("someServerScript.ps1","bash someServerScript.sh", {"asynchronous": true, "args":["-port 8080"] },{"port":8080 , "startupTime": 20, "path": "some/path/", "interval": 2})
executeCommand("node", "node" ,{"args": ["-v"]})
--


